export async function getAllFlights() {
  return [
    {
      identifier: 1,
      origin: 'Costa Rica',
      destination: 'Florida',
      outboundDate: new Date(Date.parse('2020-03-20')),
      inboundDate: new Date(Date.parse('2020-03-28')),
      passengerAmount: 13,
      passengerTotal: 40,
    },
    {
      identifier: 2,
      origin: 'Costa Rica',
      destination: 'Spain',
      outboundDate: new Date(Date.parse('2020-03-20')),
      inboundDate: new Date(Date.parse('2020-03-28')),
      passengerAmount: 13,
      passengerTotal: 40,
    },
    {
      identifier: 3,
      origin: 'Costa Rica',
      destination: 'Spain',
      outboundDate: new Date(Date.parse('2020-03-20')),
      inboundDate: new Date(Date.parse('2020-03-28')),
      passengerAmount: 13,
      passengerTotal: 40,
    },
    {
      identifier: 4,
      origin: 'Costa Rica',
      destination: 'Spain',
      outboundDate: new Date(Date.parse('2020-03-20')),
      inboundDate: new Date(Date.parse('2020-03-28')),
      passengerAmount: 13,
      passengerTotal: 40,
    },
    {
      identifier: 5,
      origin: 'Costa Rica',
      destination: 'Spain',
      outboundDate: new Date(Date.parse('2020-03-20')),
      inboundDate: new Date(Date.parse('2020-03-28')),
      passengerAmount: 13,
      passengerTotal: 40,
    },
    {
      identifier: 6,
      origin: 'Costa Rica',
      destination: 'Spain',
      outboundDate: new Date(Date.parse('2020-03-20')),
      inboundDate: new Date(Date.parse('2020-03-28')),
      passengerAmount: 13,
      passengerTotal: 40,
    },
    {
      identifier: 7,
      origin: 'Costa Rica',
      destination: 'Spain',
      outboundDate: new Date(Date.parse('2020-03-20')),
      inboundDate: new Date(Date.parse('2020-03-28')),
      passengerAmount: 13,
      passengerTotal: 40,
    },
    {
      identifier: 8,
      origin: 'Costa Rica',
      destination: 'Spain',
      outboundDate: new Date(Date.parse('2020-03-20')),
      inboundDate: new Date(Date.parse('2020-03-28')),
      passengerAmount: 13,
      passengerTotal: 40,
    },
    {
      identifier: 9,
      origin: 'Costa Rica',
      destination: 'Spain',
      outboundDate: new Date(Date.parse('2020-03-20')),
      inboundDate: new Date(Date.parse('2020-03-28')),
      passengerAmount: 13,
      passengerTotal: 40,
    },
    {
      identifier: 10,
      origin: 'Costa Rica',
      destination: 'Spain',
      outboundDate: new Date(Date.parse('2020-03-20')),
      inboundDate: new Date(Date.parse('2020-03-28')),
      passengerAmount: 13,
      passengerTotal: 40,
    },
    {
      identifier: 11,
      origin: 'Costa Rica',
      destination: 'Spain',
      outboundDate: new Date(Date.parse('2020-03-20')),
      inboundDate: new Date(Date.parse('2020-03-28')),
      passengerAmount: 13,
      passengerTotal: 40,
    },
  ]
}
